import org.jetbrains.kotlin.gradle.dsl.JvmTarget
import java.util.Properties

plugins {
    alias(libs.plugins.kotlin.multiplatform)
    alias(libs.plugins.android.application)
    alias(libs.plugins.compose.multiplatform)
    alias(libs.plugins.compose.compiler)
    alias(libs.plugins.kotlin.serialization)
}

// Azure APIM subscription key, resolved the same way :app resolves it — local.properties
// first, then the environment. Takes Project explicitly: top-level functions in a Kotlin DSL
// script cannot reach the script's implicit Project receiver.
fun resolveSubscriptionKey(project: Project): String {
    val props = Properties()
    val propsFile = project.rootProject.file("local.properties")
    if (propsFile.exists()) {
        propsFile.inputStream().use { props.load(it) }
    }
    val key = props.getProperty("twg.subscriptionKey") ?: System.getenv("TWG_SUBSCRIPTION_KEY")
    if (key.isNullOrBlank()) {
        project.logger.warn(
            "WARNING: twg.subscriptionKey is not set in local.properties and " +
                "TWG_SUBSCRIPTION_KEY is not in the environment. API calls will fail with 401."
        )
        return ""
    }
    return key.trim()
}

// BuildConfig is Android-only, so it cannot carry the key to the iOS target. Generate a
// Kotlin constant into commonMain instead. Output lands under build/, so it is never
// committed.
val generateSubscriptionKey by tasks.registering {
    val subscriptionKey = resolveSubscriptionKey(project)
    val outputDir = layout.buildDirectory.dir("generated/twgConfig")

    inputs.property("subscriptionKey", subscriptionKey)
    outputs.dir(outputDir)

    doLast {
        val escaped = subscriptionKey.replace("\\", "\\\\").replace("\"", "\\\"")
        val file = outputDir.get().asFile
            .resolve("nz/co/warehouseandroidtest/kmp/network/SubscriptionKey.kt")
        file.parentFile.mkdirs()
        file.writeText(
            """
            package nz.co.warehouseandroidtest.kmp.network

            // Generated by the :composeApp:generateSubscriptionKey task. Do not edit.
            internal const val SUBSCRIPTION_KEY: String = "$escaped"

            """.trimIndent()
        )
    }
}

kotlin {
    androidTarget {
        compilerOptions {
            jvmTarget.set(JvmTarget.JVM_17)
        }
    }

    // No iosX64: Compose Multiplatform 1.12 stopped publishing artifacts for the Intel-Mac
    // simulator target, so declaring it only produces unresolvable dependencies.
    listOf(
        iosArm64(),
        iosSimulatorArm64(),
    ).forEach { iosTarget ->
        iosTarget.binaries.framework {
            // Must match the framework name imported by iosApp/iOSApp.swift.
            baseName = "ComposeApp"
            isStatic = true
        }
    }

    sourceSets {
        commonMain {
            // Passing the task provider carries the dependency, so no explicit dependsOn.
            kotlin.srcDir(generateSubscriptionKey)

            dependencies {
                implementation(compose.runtime)
                implementation(compose.foundation)
                implementation(compose.material3)
                implementation(compose.ui)
                implementation(compose.components.resources)
                implementation(libs.kotlinx.serialization.json)
                implementation(libs.multiplatform.settings)
                implementation(libs.ktor.client.core)
                implementation(libs.ktor.client.content.negotiation)
                implementation(libs.ktor.serialization.kotlinx.json)
            }
        }

        commonTest.dependencies {
            implementation(libs.kotlin.test)
            // MapSettings, an in-memory Settings for exercising SessionStore without a device.
            implementation(libs.multiplatform.settings.test)
            implementation(libs.kotlinx.coroutines.test)
            implementation(libs.ktor.client.mock)
        }

        androidMain.dependencies {
            implementation(compose.preview)
            implementation(libs.androidx.activity.compose)
            implementation(libs.androidx.security.crypto)
            implementation(libs.ktor.client.okhttp)
        }

        iosMain.dependencies {
            implementation(libs.ktor.client.darwin)
        }
    }
}

android {
    namespace = "nz.co.warehouseandroidtest.kmp"
    compileSdk = libs.versions.compileSdk.get().toInt()

    sourceSets["main"].manifest.srcFile("src/androidMain/AndroidManifest.xml")
    sourceSets["main"].res.srcDirs("src/androidMain/res")

    defaultConfig {
        // Suffixed so this installs alongside :app during the migration. Drop the
        // suffix at cutover, once :app is removed.
        applicationId = "nz.co.warehouseandroidtest.kmp"
        minSdk = libs.versions.minSdk.get().toInt()
        targetSdk = libs.versions.targetSdk.get().toInt()
        versionCode = 1
        versionName = "1.0"
    }

    buildTypes {
        release {
            isMinifyEnabled = false
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
}

dependencies {
    debugImplementation(compose.uiTooling)
}
